# Generated by Django 6.0.4 on 2026-04-25 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Delivery charges for this product. Leave empty or 0 for free shipping.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
