# Generated by Django 6.0.4 on 2026-04-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery charges for this specific item', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ghostorder',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='List of ordered items with product details'),
        ),
        migrations.AlterField(
            model_name='ghostorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
