# Generated by Django 6.0.4 on 2026-04-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, help_text='e.g., Leopards, TCS, Call Courier', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Courier tracking number', max_length=100, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('status_updates', models.JSONField(default=list, help_text='List of status updates with timestamps and notes')),
                ('current_location', models.CharField(blank=True, help_text='Current location of shipment', max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.ghostorder')),
            ],
            options={
                'verbose_name': 'Order Tracking',
                'verbose_name_plural': 'Order Tracking',
            },
        ),
    ]
